[[classes]]
id = "fighter"
name = "Fighter"
description = "A master of martial combat, skilled with a variety of weapons and armor"


[[classes]]
id = "bard"
name = "Bard"
description = "An inspiring magician whose power echoes the music of creation"
